# Usign the Clean Blog theme

title: ENS-CFM Data Science Chair
author: data-ens
email: gabriel.peyre@ens.fr
description: ENS-CFM Data Science Chair
baseurl: ""
url: "http://data-ens.github.io/"
github_username:  data-ens

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Data Sciences @ ENS
gems:
  - jekyll-feed
  - jekyll-paginate
